repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black alice tests
        language: system
        types: [ python ]
        require_serial: true
        fail_fast: true

      - id: flake8
        name: flake8
        entry: flake8 alice tests
        language: system
        types: [ python ]
        require_serial: true
        fail_fast: true

      - id: pyupgrade
        name: Pyupgrade
        entry: pyupgrade --py36-plus
        types: [ python ]
        language: system
        exclude: ^docs/.*$
        fail_fast: true

      - id: isort
        name: isort
        entry: isort alice tests
        language: system
        types: [ python ]
        require_serial: true
        fail_fast: true

