name: ci

on:
  pull_request:
    paths-ignore:
      - '*.md'
      - 'alice/VERSION'
    branches:
      - main

env:
  ONBOARDING_API_KEY: ${{ secrets.API_KEY_TESTING_PRO_ONBOARDING_ALL_FEATURES }}
  ONBOARDING_SANDBOX_TOKEN: ${{ secrets.ONBOARDING_SANDBOX_TOKEN }}
  CONCURRENT_TESTING: True

jobs:
  ci:
    strategy:
      max-parallel: 4
      matrix:
        os: [ macOS-latest, ubuntu-latest ]
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: '**/*requirements.txt'
      - name: Install Requirements
        run: |
          pip install lume
          lume -install
      - name: Lint
        run: lume -lint
      - name: Static Analysis
        run: lume -static-analysis
      - name: Check Requirements
        run: lume -check-requirements
      - name: Test [pytest]
        run: lume -test
      - name: Example [Onboarding]
        run: python examples/onboarding.py
      - name: Example [Onboarding Get Users]
        run: python examples/onboarding_get_users.py
      - name: Example [Onboarding Report V0]
        run: python examples/onboarding_report_v0.py
      - name: Example [Onboarding with Identification]
        run: python examples/onboarding_with_identification.py
      - name: Example [Onboarding with user matching]
        run: python examples/onboarding_with_user_matching.py
      - name: Example [Onboarding with Certificate]
        run: python examples/onboarding_with_certificate.py
      - name: Example [Onboarding with Screening]
        run: python examples/onboarding_with_screening.py
      - name: Example [Auth]
        run: python examples/auth.py
      - name: Example [Sandbox]
        run: python examples/sandbox.py
      - name: Example [Request]
        run: python examples/onboarding_request.py