name: pypi

on:
  release:
    types: [published]

env:
  ONBOARDING_API_KEY: ${{ secrets.API_KEY_TESTING_PRO_ONBOARDING_ALL_FEATURES }}
  ONBOARDING_SANDBOX_TOKEN: ${{ secrets.ONBOARDING_SANDBOX_TOKEN }}
  CONCURRENT_TESTING: True

jobs:
  ci:
    strategy:
      max-parallel: 4
      matrix:
        os: [ macOS-latest, ubuntu-latest ]
        python-version: [3.7, 3.8, 3.9]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: '**/*requirements.txt'
      - name: Install Requirements
        run: |
          pip install lume
          lume -install
      - name: Lint
        run: lume -lint
      - name: Test [pytest]
        run: lume -test
      - name: Example [Onboarding]
        run: python examples/onboarding.py
      - name: Example [Onboarding with Identification]
        run: python examples/onboarding_with_identification.py
      - name: Example [Onboarding with Certificate]
        run: python examples/onboarding_with_certificate.py
      - name: Example [Onboarding with Screening]
        run: python examples/onboarding_with_screening.py
      - name: Example [Auth]
        run: python examples/auth.py
      - name: Example [Sandbox]
        run: python examples/sandbox.py

  get-version:
    uses: alice-biometrics/actions/.github/workflows/get-version.yml@main
    with:
      type: release
      
  publish:
    needs: [ci, get-version]
    uses: alice-biometrics/actions/.github/workflows/publish-pypi.yml@main
    with:
      package_name: alice-onboarding
      version: ${{ needs.get-version.outputs.version }}
      folder: alice
    secrets:
      username: ${{ secrets.PYPI_TOKEN_USERNAME }}
      password: ${{ secrets.PYPI_TOKEN_PASSWORD_ALICE_ONBOARDING }}
      github_access_token: ${{ secrets.PUBLIC_GITHUB_ACCESS_TOKEN }}


